version: '3'
services:
  # Node.js service
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=${MONGO_URI}
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - mongo

  # MongoDB service
  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo-data:
